name: mcrafter
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - pillow
  - networkx
  - pip:
      - openai
      - tiktoken
      - pydantic
      - transformers
      - torch
      - torchvision
      - torchaudio
      - scikit-learn
      - pyvis
      - tqdm
      - imageio
      - requests
      - regex
      - pygame
      - matplotlib